### ISSUE TITLE
코드리뷰 요청드립니다!

### ISSUE THREAD

**Issue by ferrariRoma** [ferrariRoma/react_second_assignment#1]
리액트가 처음이라 전체적인 코드 구성이 적절한지에 대한 부분을 피드백 받고 싶습니다.

**Comment by leedaeho1188** [comment]
1. src 폴더안에 redux 폴더처럼 다른 파일들을 관리하는 폴더를 만들어서 그 안에 파일들을 옮겨서 관리하면 좋을 것 같습니다. 지금은 파일이 적지만 나중에는 프로젝트가 복잡해지면 파일들도 많아져서 폴더를 만들어서 파일을 분리하지 않으면 파일을 관리하기 어렵습니다.
아래는 폴더 예시 및 설명입니다.
- pages = 페이지 컴포넌트 파일을 관리하는 폴더
- components = 페이지 컴포넌트의 하위 컴포넌트를 관리하는 폴더
- shared = 여러 컴포넌트에서 공통적으로 사용되는 파일을 관리하는 폴더 

2. redux는 잘 사용하신 것 같습니다. 리덕스의대한 기본적이 개념을 이해하셨다면 다음번에는 redux-toolkit을 사용하시는걸 추천드립니다.

3. App.jsx가 렌더링 될때마다 dictionary data get요청을하는데 Home.jsx가 렌더링될때마다 get요청을하는 로직으로 진행하면 코드를 더 효율적으로 짤 수 있을 것 같습니다. 

처음인데도 잘 하신것 같습니다. 수고하셨습니다.
